spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:kakaopaysec;MODE=MYSQL
    driverClassName: org.h2.Driver
    password: ''
  redis:
    host: localhost
    port: '6379'
